// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteConfigData, DeleteConfigErrors, DeleteConfigResponses, GetConfigsData, GetConfigsErrors, GetConfigsResponses, GetConnectData, GetConnectResponses, GetHealthData, GetHealthResponses, GetLicenseCheckData, GetLicenseCheckResponses, GetLicenseClearData, GetLicenseClearResponses, GetRootData, GetRootResponses, PostConfigData, PostConfigErrors, PostConfigResponses, PostExportData, PostExportErrors, PostExportResponses, PostExtractAllData, PostExtractAllErrors, PostExtractAllResponses, PostExtractData, PostExtractErrors, PostExtractResponses, PostGuessRegexData, PostGuessRegexErrors, PostGuessRegexResponses, PostVisionDetectSymbolsData, PostVisionDetectSymbolsErrors, PostVisionDetectSymbolsResponses, PostVisionExportData, PostVisionExportErrors, PostVisionExportResponses, PostVisionExtractLegendData, PostVisionExtractLegendErrors, PostVisionExtractLegendResponses, PostVisionRenderPageData, PostVisionRenderPageErrors, PostVisionRenderPageResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new TextHunterClient()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class TextHunterClient extends HeyApiClient {
    public static readonly __registry = new HeyApiRegistry<TextHunterClient>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        TextHunterClient.__registry.set(this, args?.key);
    }
    
    /**
     * List Configs
     *
     * List all saved configs for the current user.
     */
    public getConfigs<ThrowOnError extends boolean = false>(options?: Options<GetConfigsData, ThrowOnError>) {
        return (options?.client ?? this.client).get<GetConfigsResponses, GetConfigsErrors, ThrowOnError>({ url: '/v1/history/configs', ...options });
    }
    
    /**
     * Save Config
     *
     * Save or update a named regex config.
     */
    public postConfig<ThrowOnError extends boolean = false>(options: Options<PostConfigData, ThrowOnError>) {
        return (options.client ?? this.client).post<PostConfigResponses, PostConfigErrors, ThrowOnError>({
            url: '/v1/history/configs',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete Config
     *
     * Delete a saved config by id.
     */
    public deleteConfig<ThrowOnError extends boolean = false>(options: Options<DeleteConfigData, ThrowOnError>) {
        return (options.client ?? this.client).delete<DeleteConfigResponses, DeleteConfigErrors, ThrowOnError>({ url: '/v1/history/configs/{config_id}', ...options });
    }
    
    /**
     * Health Check
     *
     * Health check endpoint.
     */
    public getHealth<ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) {
        return (options?.client ?? this.client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });
    }
    
    /**
     * Extract Data
     *
     * Run regex extraction on provided text content.
     *
     * Returns a preview of the first 10 matches.
     */
    public postExtract<ThrowOnError extends boolean = false>(options: Options<PostExtractData, ThrowOnError>) {
        return (options.client ?? this.client).post<PostExtractResponses, PostExtractErrors, ThrowOnError>({
            url: '/extract',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Extract All Data
     *
     * Run regex extraction and return all matches.
     *
     * Use this endpoint when preparing for export.
     */
    public postExtractAll<ThrowOnError extends boolean = false>(options: Options<PostExtractAllData, ThrowOnError>) {
        return (options.client ?? this.client).post<PostExtractAllResponses, PostExtractAllErrors, ThrowOnError>({
            url: '/extract-all',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Generate Regex
     *
     * Generate a regex pattern from example strings.
     *
     * Requires at least 2 examples.
     */
    public postGuessRegex<ThrowOnError extends boolean = false>(options: Options<PostGuessRegexData, ThrowOnError>) {
        return (options.client ?? this.client).post<PostGuessRegexResponses, PostGuessRegexErrors, ThrowOnError>({
            url: '/guess-regex',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Export Excel
     *
     * Generate and stream an Excel file from match results.
     */
    public postExport<ThrowOnError extends boolean = false>(options: Options<PostExportData, ThrowOnError>) {
        return (options.client ?? this.client).post<PostExportResponses, PostExportErrors, ThrowOnError>({
            url: '/export',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Render Pdf Page
     *
     * Render a single PDF page to a base64 PNG.
     *
     * Used by the frontend legend annotation canvas.
     */
    public postVisionRenderPage<ThrowOnError extends boolean = false>(options: Options<PostVisionRenderPageData, ThrowOnError>) {
        return (options.client ?? this.client).post<PostVisionRenderPageResponses, PostVisionRenderPageErrors, ThrowOnError>({
            url: '/vision/render-page',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Extract Legend
     *
     * Extract symbol templates from a legend page image.
     *
     * If bounding_boxes is provided, crops those regions.
     * Otherwise, runs automatic contour-based segmentation.
     */
    public postVisionExtractLegend<ThrowOnError extends boolean = false>(options: Options<PostVisionExtractLegendData, ThrowOnError>) {
        return (options.client ?? this.client).post<PostVisionExtractLegendResponses, PostVisionExtractLegendErrors, ThrowOnError>({
            url: '/vision/extract-legend',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Detect Symbols
     *
     * Detect P&ID symbols across all pages of a target PDF.
     *
     * Returns detections with bounding boxes, confidence scores, and nearby tags.
     * Annotated page images are included in the response.
     */
    public postVisionDetectSymbols<ThrowOnError extends boolean = false>(options: Options<PostVisionDetectSymbolsData, ThrowOnError>) {
        return (options.client ?? this.client).post<PostVisionDetectSymbolsResponses, PostVisionDetectSymbolsErrors, ThrowOnError>({
            url: '/vision/detect-symbols',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Export Vision Excel
     *
     * Export symbol detection results to Excel.
     */
    public postVisionExport<ThrowOnError extends boolean = false>(options: Options<PostVisionExportData, ThrowOnError>) {
        return (options.client ?? this.client).post<PostVisionExportResponses, PostVisionExportErrors, ThrowOnError>({
            url: '/vision/export',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Root
     *
     * Root endpoint with API info.
     */
    public getRoot<ThrowOnError extends boolean = false>(options?: Options<GetRootData, ThrowOnError>) {
        return (options?.client ?? this.client).get<GetRootResponses, unknown, ThrowOnError>({ url: '/', ...options });
    }
    
    /**
     * Connect
     *
     * Return connection info for Tauri sidecar.
     */
    public getConnect<ThrowOnError extends boolean = false>(options?: Options<GetConnectData, ThrowOnError>) {
        return (options?.client ?? this.client).get<GetConnectResponses, unknown, ThrowOnError>({ url: '/v1/connect', ...options });
    }
    
    /**
     * Check License
     *
     * Check local version against the external API.
     *
     * Returns:
     * dict with version validation status
     */
    public getLicenseCheck<ThrowOnError extends boolean = false>(options?: Options<GetLicenseCheckData, ThrowOnError>) {
        return (options?.client ?? this.client).get<GetLicenseCheckResponses, unknown, ThrowOnError>({ url: '/v1/license/check', ...options });
    }
    
    /**
     * Clear License Endpoint
     *
     * Clear cached license (for testing).
     *
     * Returns:
     * dict with status message
     */
    public getLicenseClear<ThrowOnError extends boolean = false>(options?: Options<GetLicenseClearData, ThrowOnError>) {
        return (options?.client ?? this.client).get<GetLicenseClearResponses, unknown, ThrowOnError>({ url: '/v1/license/clear', ...options });
    }
}
