// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * BoundingBox
 *
 * Pixel bounding box in image coordinates.
 */
export type BoundingBox = {
    /**
     * X
     */
    x: number;
    /**
     * Y
     */
    y: number;
    /**
     * Width
     */
    width: number;
    /**
     * Height
     */
    height: number;
};

/**
 * ConfigCreate
 *
 * Request payload for creating or updating a config.
 */
export type ConfigCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Keyword Regex
     */
    keyword_regex: string;
    /**
     * File Identifier Regex
     */
    file_identifier_regex?: string | null;
};

/**
 * ConfigResponse
 *
 * Response payload for a saved config.
 */
export type ConfigResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Keyword Regex
     */
    keyword_regex: string;
    /**
     * File Identifier Regex
     */
    file_identifier_regex?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Modified
     */
    modified: string;
};

/**
 * ExportRequest
 *
 * Request payload for Excel export.
 */
export type ExportRequest = {
    /**
     * Matches
     */
    matches: Array<MatchResult>;
    /**
     * Include Context
     */
    include_context?: boolean;
};

/**
 * ExtractionAllResponse
 *
 * Response from extract-all endpoint.
 */
export type ExtractionAllResponse = {
    /**
     * Matches
     */
    matches: Array<MatchResult>;
    /**
     * Total Count
     */
    total_count: number;
};

/**
 * ExtractionRequest
 *
 * Request payload for text extraction.
 */
export type ExtractionRequest = {
    /**
     * Filenames
     *
     * List of PDF filenames
     */
    filenames: Array<string>;
    /**
     * File Identifier Regex
     *
     * Regex to extract metadata from filenames
     */
    file_identifier_regex?: string | null;
    /**
     * Keyword Regex
     *
     * Regex pattern to match in text
     */
    keyword_regex: string;
    /**
     * Text Content
     *
     * Map of filename -> {page_number: text_content}
     */
    text_content: {
        [key: string]: {
            [key: string]: string;
        };
    };
};

/**
 * ExtractionResponse
 *
 * Response from extraction endpoint.
 */
export type ExtractionResponse = {
    /**
     * Matches
     */
    matches: Array<MatchResult>;
    /**
     * Total Count
     */
    total_count: number;
    /**
     * Preview Count
     *
     * Number of matches in preview
     */
    preview_count?: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 *
 * Response from health check endpoint.
 */
export type HealthResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Timestamp
     */
    timestamp: string;
};

/**
 * LegendExtractRequest
 *
 * Extract symbol templates from a legend PDF page rendered as an image.
 */
export type LegendExtractRequest = {
    /**
     * Image B64
     *
     * Base64-encoded PNG of the legend page
     */
    image_b64: string;
    /**
     * Bounding Boxes
     *
     * User-annotated regions. If None, auto-segmentation is attempted.
     */
    bounding_boxes?: Array<BoundingBox> | null;
    /**
     * Symbol Names
     *
     * Names for each bounding_box (required when bounding_boxes is provided).
     */
    symbol_names?: Array<string> | null;
};

/**
 * LegendExtractResponse
 *
 * Extracted templates from a legend page.
 */
export type LegendExtractResponse = {
    /**
     * Templates
     */
    templates: Array<SymbolTemplate>;
    /**
     * Annotated Image B64
     *
     * Legend with detected regions highlighted
     */
    annotated_image_b64: string;
};

/**
 * MatchResult
 *
 * A single match result.
 */
export type MatchResult = {
    /**
     * Source File
     */
    source_file: string;
    /**
     * Project Id
     */
    project_id?: string | null;
    /**
     * Sheet No
     */
    sheet_no?: string | null;
    /**
     * Page
     */
    page: number;
    /**
     * Match Found
     */
    match_found: string;
    /**
     * Context
     *
     * ±20 chars around the match
     */
    context: string;
    /**
     * Preset Name
     *
     * Name of the saved preset used for this extraction
     */
    preset_name?: string | null;
};

/**
 * RegexGuessRequest
 *
 * Request payload for regex generation from examples.
 */
export type RegexGuessRequest = {
    /**
     * Examples
     *
     * Example strings to generate regex from
     */
    examples: Array<string>;
};

/**
 * RegexGuessResponse
 *
 * Response from regex guess endpoint.
 */
export type RegexGuessResponse = {
    /**
     * Pattern
     *
     * Generated regex pattern
     */
    pattern: string;
    /**
     * Explanation
     *
     * Explanation of the generated pattern
     */
    explanation: string;
    /**
     * Test Results
     *
     * Which examples match the generated pattern
     */
    test_results: {
        [key: string]: boolean;
    };
};

/**
 * RenderPageRequest
 *
 * Render a single PDF page to an image.
 */
export type RenderPageRequest = {
    /**
     * Pdf B64
     *
     * Base64-encoded PDF bytes
     */
    pdf_b64: string;
    /**
     * Page
     *
     * 1-based page number to render
     */
    page?: number;
    /**
     * Dpi
     *
     * Rendering resolution
     */
    dpi?: number;
};

/**
 * RenderPageResponse
 *
 * Rendered page image.
 */
export type RenderPageResponse = {
    /**
     * Image B64
     */
    image_b64: string;
    /**
     * Page
     */
    page: number;
    /**
     * Width
     */
    width: number;
    /**
     * Height
     */
    height: number;
    /**
     * Total Pages
     */
    total_pages: number;
};

/**
 * SymbolDetectRequest
 *
 * Detect symbols across pages of a target P&ID PDF.
 */
export type SymbolDetectRequest = {
    /**
     * Pdf B64
     *
     * Base64-encoded PDF file to scan
     */
    pdf_b64: string;
    /**
     * Templates
     *
     * Symbol templates to search for
     */
    templates: Array<SymbolTemplate>;
    /**
     * Dpi
     *
     * PDF rendering resolution
     */
    dpi?: number;
    /**
     * Threshold
     *
     * Confidence threshold
     */
    threshold?: number;
    /**
     * Scale Range
     */
    scale_range?: [
        number,
        number
    ];
    /**
     * Enable Rotation
     *
     * Search rotated variants (4× slower)
     */
    enable_rotation?: boolean;
    /**
     * Nearby Text Radius Px
     */
    nearby_text_radius_px?: number;
    /**
     * Existing Text Content
     *
     * Pre-extracted text from the PDF worker (filename -> page -> text). Used for tag association; skips re-extraction when provided.
     */
    existing_text_content?: {
        [key: string]: {
            [key: string]: string;
        };
    } | null;
};

/**
 * SymbolDetectResponse
 *
 * All detections across the entire P&ID PDF.
 */
export type SymbolDetectResponse = {
    /**
     * Results
     */
    results: Array<SymbolDetectionResult>;
    /**
     * Total Count
     */
    total_count: number;
    /**
     * Pages Processed
     */
    pages_processed: number;
    /**
     * Annotated Pages B64
     *
     * Base64 PNG of each processed page with bounding boxes drawn
     */
    annotated_pages_b64?: Array<string>;
};

/**
 * SymbolDetectionResult
 *
 * A single symbol detection hit.
 */
export type SymbolDetectionResult = {
    /**
     * Symbol Name
     */
    symbol_name: string;
    /**
     * Page
     */
    page: number;
    bbox: BoundingBox;
    /**
     * Confidence
     */
    confidence: number;
    /**
     * Associated Tags
     */
    associated_tags?: Array<string>;
    /**
     * Scale
     */
    scale?: number;
    /**
     * Angle Deg
     */
    angle_deg?: number;
};

/**
 * SymbolTemplate
 *
 * A named symbol template encoded as a base64 PNG image.
 */
export type SymbolTemplate = {
    /**
     * Name
     *
     * Human-readable symbol name, e.g. 'Control Valve'
     */
    name: string;
    /**
     * Image B64
     *
     * Base64-encoded PNG of the template image
     */
    image_b64: string;
    /**
     * Source Legend Page
     *
     * Legend page this template was extracted from
     */
    source_legend_page?: number | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VisionExportRequest
 *
 * Export symbol detection results to Excel.
 */
export type VisionExportRequest = {
    /**
     * Results
     */
    results: Array<SymbolDetectionResult>;
    /**
     * Include Annotated Images
     */
    include_annotated_images?: boolean;
};

export type GetConfigsData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/history/configs';
};

export type GetConfigsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConfigsError = GetConfigsErrors[keyof GetConfigsErrors];

export type GetConfigsResponses = {
    /**
     * Response Get Configs
     *
     * Successful Response
     */
    200: Array<ConfigResponse>;
};

export type GetConfigsResponse = GetConfigsResponses[keyof GetConfigsResponses];

export type PostConfigData = {
    body: ConfigCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/history/configs';
};

export type PostConfigErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostConfigError = PostConfigErrors[keyof PostConfigErrors];

export type PostConfigResponses = {
    /**
     * Successful Response
     */
    200: ConfigResponse;
};

export type PostConfigResponse = PostConfigResponses[keyof PostConfigResponses];

export type DeleteConfigData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Config Id
         */
        config_id: string;
    };
    query?: never;
    url: '/v1/history/configs/{config_id}';
};

export type DeleteConfigErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteConfigError = DeleteConfigErrors[keyof DeleteConfigErrors];

export type DeleteConfigResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteConfigResponse = DeleteConfigResponses[keyof DeleteConfigResponses];

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type PostExtractData = {
    body: ExtractionRequest;
    path?: never;
    query?: never;
    url: '/extract';
};

export type PostExtractErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostExtractError = PostExtractErrors[keyof PostExtractErrors];

export type PostExtractResponses = {
    /**
     * Successful Response
     */
    200: ExtractionResponse;
};

export type PostExtractResponse = PostExtractResponses[keyof PostExtractResponses];

export type PostExtractAllData = {
    body: ExtractionRequest;
    path?: never;
    query?: never;
    url: '/extract-all';
};

export type PostExtractAllErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostExtractAllError = PostExtractAllErrors[keyof PostExtractAllErrors];

export type PostExtractAllResponses = {
    /**
     * Successful Response
     */
    200: ExtractionAllResponse;
};

export type PostExtractAllResponse = PostExtractAllResponses[keyof PostExtractAllResponses];

export type PostGuessRegexData = {
    body: RegexGuessRequest;
    path?: never;
    query?: never;
    url: '/guess-regex';
};

export type PostGuessRegexErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostGuessRegexError = PostGuessRegexErrors[keyof PostGuessRegexErrors];

export type PostGuessRegexResponses = {
    /**
     * Successful Response
     */
    200: RegexGuessResponse;
};

export type PostGuessRegexResponse = PostGuessRegexResponses[keyof PostGuessRegexResponses];

export type PostExportData = {
    body: ExportRequest;
    path?: never;
    query?: never;
    url: '/export';
};

export type PostExportErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostExportError = PostExportErrors[keyof PostExportErrors];

export type PostExportResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PostVisionRenderPageData = {
    body: RenderPageRequest;
    path?: never;
    query?: never;
    url: '/vision/render-page';
};

export type PostVisionRenderPageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostVisionRenderPageError = PostVisionRenderPageErrors[keyof PostVisionRenderPageErrors];

export type PostVisionRenderPageResponses = {
    /**
     * Successful Response
     */
    200: RenderPageResponse;
};

export type PostVisionRenderPageResponse = PostVisionRenderPageResponses[keyof PostVisionRenderPageResponses];

export type PostVisionExtractLegendData = {
    body: LegendExtractRequest;
    path?: never;
    query?: never;
    url: '/vision/extract-legend';
};

export type PostVisionExtractLegendErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostVisionExtractLegendError = PostVisionExtractLegendErrors[keyof PostVisionExtractLegendErrors];

export type PostVisionExtractLegendResponses = {
    /**
     * Successful Response
     */
    200: LegendExtractResponse;
};

export type PostVisionExtractLegendResponse = PostVisionExtractLegendResponses[keyof PostVisionExtractLegendResponses];

export type PostVisionDetectSymbolsData = {
    body: SymbolDetectRequest;
    path?: never;
    query?: never;
    url: '/vision/detect-symbols';
};

export type PostVisionDetectSymbolsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostVisionDetectSymbolsError = PostVisionDetectSymbolsErrors[keyof PostVisionDetectSymbolsErrors];

export type PostVisionDetectSymbolsResponses = {
    /**
     * Successful Response
     */
    200: SymbolDetectResponse;
};

export type PostVisionDetectSymbolsResponse = PostVisionDetectSymbolsResponses[keyof PostVisionDetectSymbolsResponses];

export type PostVisionExportData = {
    body: VisionExportRequest;
    path?: never;
    query?: never;
    url: '/vision/export';
};

export type PostVisionExportErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostVisionExportError = PostVisionExportErrors[keyof PostVisionExportErrors];

export type PostVisionExportResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetRootData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetRootResponses = {
    /**
     * Response Get Root
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type GetRootResponse = GetRootResponses[keyof GetRootResponses];

export type GetConnectData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/connect';
};

export type GetConnectResponses = {
    /**
     * Response Get Connect
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetConnectResponse = GetConnectResponses[keyof GetConnectResponses];

export type GetLicenseCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/license/check';
};

export type GetLicenseCheckResponses = {
    /**
     * Response Get License Check
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetLicenseCheckResponse = GetLicenseCheckResponses[keyof GetLicenseCheckResponses];

export type GetLicenseClearData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/license/clear';
};

export type GetLicenseClearResponses = {
    /**
     * Response Get License Clear
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetLicenseClearResponse = GetLicenseClearResponses[keyof GetLicenseClearResponses];
