/**
 * Tests for the RegexConfig component.
 * Covers error display, pattern generation flow, and extract emit.
 */
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { mount } from '@vue/test-utils';
import RegexConfig from '@/components/RegexConfig.vue';

// Mock the api service so tests don't make real HTTP calls
vi.mock('@/services/api.ts', () => ({
  guessRegex: vi.fn(),
}));

// Mock @tauri-apps/plugin-http to avoid import errors in jsdom
vi.mock('@tauri-apps/plugin-http', () => ({ fetch: vi.fn() }));

describe('RegexConfig', () => {
  let guessRegexMock: ReturnType<typeof vi.fn>;

  beforeEach(async () => {
    vi.clearAllMocks();
    const apiModule = await import('@/services/api.ts');
    guessRegexMock = apiModule.guessRegex as ReturnType<typeof vi.fn>;
  });

  it('renders in helper (AI) mode by default', () => {
    const wrapper = mount(RegexConfig);
    expect(wrapper.text()).toContain('AI Pattern Generator');
    expect(wrapper.text()).toContain('Example');
  });

  it('shows validation error when fewer than 2 examples are provided', async () => {
    const wrapper = mount(RegexConfig);

    // Clear the pre-filled example inputs so only 0 filled examples remain
    const inputs = wrapper.findAll('input[type="text"]');
    for (const input of inputs) {
      await input.setValue('');
    }

    await wrapper.find('button.btn-accent').trigger('click');

    expect(wrapper.text()).toContain('at least 2 examples');
    expect(guessRegexMock).not.toHaveBeenCalled();
  });

  it('displays the generated pattern on success', async () => {
    guessRegexMock.mockResolvedValueOnce({
      pattern: '\\d+"-[A-Z]+-\\d+',
      explanation: 'Regex generated by TextHunter from examples',
      test_results: { '10"-FG-001': true, '2"-CWS-505': true },
    });

    const wrapper = mount(RegexConfig);

    const inputs = wrapper.findAll('input[type="text"]');
    await inputs[0].setValue('10"-FG-001');
    await inputs[1].setValue('2"-CWS-505');

    await wrapper.find('button.btn-accent').trigger('click');
    // Wait for the async guessRegex call to resolve
    await new Promise((r) => setTimeout(r, 0));
    await wrapper.vm.$nextTick();

    expect(wrapper.text()).toContain('\\d+"-[A-Z]+-\\d+');
  });

  it('shows error message when pattern generation fails', async () => {
    guessRegexMock.mockRejectedValueOnce(new Error('HTTP 400: At least 2 examples required'));

    const wrapper = mount(RegexConfig);

    const inputs = wrapper.findAll('input[type="text"]');
    await inputs[0].setValue('A');
    await inputs[1].setValue('B');

    await wrapper.find('button.btn-accent').trigger('click');
    await new Promise((r) => setTimeout(r, 0));
    await wrapper.vm.$nextTick();

    expect(wrapper.text()).toContain('HTTP 400: At least 2 examples required');
  });

  it('emits extract event with config when Extract Matches is clicked in manual mode', async () => {
    const wrapper = mount(RegexConfig);

    // Switch to manual mode
    const buttons = wrapper.findAll('button.toggle-btn');
    await buttons[1].trigger('click'); // "Advanced Manual Regex"

    const inputs = wrapper.findAll('input[type="text"]');
    await inputs[0].setValue('\\d+-[A-Z]+-\\d+');

    await wrapper.find('button.btn-primary').trigger('click');

    const emitted = wrapper.emitted('extract');
    expect(emitted).toBeTruthy();
    // Non-null assertion: toBeTruthy() above already guards this
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    expect(emitted![0][0]).toMatchObject({ keywordRegex: '\\d+-[A-Z]+-\\d+' });
  });
});
