/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health Check
     * @description Health check endpoint.
     */
    get: operations["health_check_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/extract": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Extract Data
     * @description Run regex extraction on provided text content.
     *
     *     Returns a preview of the first 10 matches.
     */
    post: operations["extract_data_extract_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/extract-all": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Extract All Data
     * @description Run regex extraction and return all matches.
     *
     *     Use this endpoint when preparing for export.
     */
    post: operations["extract_all_data_extract_all_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/guess-regex": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Generate Regex
     * @description Generate a regex pattern from example strings.
     *
     *     Requires at least 2 examples.
     */
    post: operations["generate_regex_guess_regex_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Export Excel
     * @description Generate and stream an Excel file from match results.
     */
    post: operations["export_excel_export_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Root
     * @description Root endpoint with API info.
     */
    get: operations["root__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * ExportRequest
     * @description Request payload for Excel export.
     */
    ExportRequest: {
      /** Matches */
      matches: components["schemas"]["MatchResult"][];
      /**
       * Include Context
       * @default true
       */
      include_context: boolean;
    };
    /**
     * ExtractionRequest
     * @description Request payload for text extraction.
     */
    ExtractionRequest: {
      /**
       * Filenames
       * @description List of PDF filenames
       */
      filenames: string[];
      /**
       * File Identifier Regex
       * @description Regex to extract metadata from filenames
       */
      file_identifier_regex?: string | null;
      /**
       * Keyword Regex
       * @description Regex pattern to match in text
       */
      keyword_regex: string;
      /**
       * Text Content
       * @description Map of filename -> {page_number: text_content}
       */
      text_content: {
        [key: string]: {
          [key: string]: string;
        };
      };
    };
    /**
     * ExtractionResponse
     * @description Response from extraction endpoint.
     */
    ExtractionResponse: {
      /** Matches */
      matches: components["schemas"]["MatchResult"][];
      /** Total Count */
      total_count: number;
      /**
       * Preview Count
       * @description Number of matches in preview
       * @default 10
       */
      preview_count: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * MatchResult
     * @description A single match result.
     */
    MatchResult: {
      /** Source File */
      source_file: string;
      /** Project Id */
      project_id?: string | null;
      /** Sheet No */
      sheet_no?: string | null;
      /** Page */
      page: number;
      /** Match Found */
      match_found: string;
      /**
       * Context
       * @description ±20 chars around the match
       */
      context: string;
    };
    /**
     * RegexGuessRequest
     * @description Request payload for regex generation from examples.
     */
    RegexGuessRequest: {
      /**
       * Examples
       * @description Example strings to generate regex from
       */
      examples: string[];
    };
    /**
     * RegexGuessResponse
     * @description Response from regex guess endpoint.
     */
    RegexGuessResponse: {
      /**
       * Pattern
       * @description Generated regex pattern
       */
      pattern: string;
      /**
       * Explanation
       * @description Explanation of the generated pattern
       */
      explanation: string;
      /**
       * Test Results
       * @description Which examples match the generated pattern
       */
      test_results: {
        [key: string]: boolean;
      };
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_check_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  extract_data_extract_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExtractionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExtractionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  extract_all_data_extract_all_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExtractionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  generate_regex_guess_regex_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegexGuessRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RegexGuessResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  export_excel_export_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExportRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  root__get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
}
